server:
  port: 8080

spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${photograph.datasource.host}:${photograph.datasource.port}/${photograph.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${photograph.datasource.username}
    password: ${photograph.datasource.password}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.platform.entity
  configuration:
    # Open hump naming
    map-underscore-to-camel-case: true


